-- MySQL Script generated by MySQL Workbench
-- 04/13/18 23:34:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CSTAlumniBoard2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CSTAlumniBoard2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CSTAlumniBoard2` DEFAULT CHARACTER SET utf8 ;
USE `CSTAlumniBoard2` ;

-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`USER` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(40) NULL DEFAULT NULL,
  `joinDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `idx_user_email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`FORUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`FORUM` (
  `forumID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `timeCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `userID` INT(11) NOT NULL,
  PRIMARY KEY (`forumID`),
  INDEX `fk_FORUM_USER1_idx` (`userID` ASC),
  CONSTRAINT `fk_FORUM_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard2`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`THREAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`THREAD` (
  `threadID` INT(11) NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(100) NULL DEFAULT NULL,
  `timeCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isPinned` TINYINT(1) NULL DEFAULT NULL,
  `userID` INT(11) NOT NULL,
  `forumID` INT(11) NOT NULL,
  PRIMARY KEY (`threadID`),
  INDEX `fk_THREAD_USER1_idx` (`userID` ASC),
  INDEX `fk_THREAD_FORUM1_idx` (`forumID` ASC),
  CONSTRAINT `fk_THREAD_FORUM1`
    FOREIGN KEY (`forumID`)
    REFERENCES `CSTAlumniBoard2`.`FORUM` (`forumID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_THREAD_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard2`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 82
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`POST` (
  `postID` INT(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `timePosted` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isPinned` TINYINT(1) NULL DEFAULT NULL,
  `isQuestion` TINYINT(1) NULL DEFAULT NULL,
  `isReply` TINYINT(1) NULL DEFAULT NULL,
  `threadID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  `originalPostID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`postID`),
  INDEX `fk_POST_THREAD1_idx` (`threadID` ASC),
  INDEX `fk_POST_USER1_idx` (`userID` ASC),
  INDEX `fk_POST_POST1_idx` (`originalPostID` ASC),
  CONSTRAINT `fk_POST_POST1`
    FOREIGN KEY (`originalPostID`)
    REFERENCES `CSTAlumniBoard2`.`POST` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POST_THREAD1`
    FOREIGN KEY (`threadID`)
    REFERENCES `CSTAlumniBoard2`.`THREAD` (`threadID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POST_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard2`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`ATTACHMENT` (
  `attachmentID` INT(11) NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(45) NULL DEFAULT NULL,
  `fileType` VARCHAR(45) NULL DEFAULT NULL,
  `postID` INT(11) NOT NULL,
  PRIMARY KEY (`attachmentID`),
  INDEX `fk_ATTACHMENT_POST1_idx` (`postID` ASC),
  CONSTRAINT `fk_ATTACHMENT_POST1`
    FOREIGN KEY (`postID`)
    REFERENCES `CSTAlumniBoard2`.`POST` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`ROLE` (
  `roleID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `userID` INT(11) NOT NULL,
  PRIMARY KEY (`roleID`),
  INDEX `fk_ROLE_USER1_idx` (`userID` ASC),
  CONSTRAINT `fk_ROLE_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard2`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`PRIVILEGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`PRIVILEGE` (
  `privilegeID` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `roleID` INT(11) NOT NULL,
  PRIMARY KEY (`privilegeID`),
  INDEX `fk_PRIVILEGE_ROLE_idx` (`roleID` ASC),
  CONSTRAINT `fk_PRIVILEGE_ROLE`
    FOREIGN KEY (`roleID`)
    REFERENCES `CSTAlumniBoard2`.`ROLE` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`FORUM_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`FORUM_SUBSCRIPTION` (
  `forumID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  INDEX `fk_forum_subscription_forum1_idx` (`forumID` ASC),
  INDEX `fk_forum_subscription_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_forum_subscription_forum1`
    FOREIGN KEY (`forumID`)
    REFERENCES `CSTAlumniBoard2`.`FORUM` (`forumID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_subscription_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard2`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard2`.`NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard2`.`NOTIFICATION` (
  `notificationID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `content` TEXT NULL,
  `link` VARCHAR(200) NULL,
  PRIMARY KEY (`notificationID`),
  INDEX `fk_Notification_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_Notification_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard2`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
