-- MySQL Script generated by MySQL Workbench
-- 04/17/18 02:00:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CSTAlumniBoard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CSTAlumniBoard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CSTAlumniBoard` DEFAULT CHARACTER SET utf8 ;
USE `CSTAlumniBoard` ;

-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`ROLE` (
  `roleID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`USER` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(40) NULL DEFAULT NULL,
  `joinDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `roleID` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `idx_user_email` (`email` ASC),
  INDEX `fk_user_role1_idx` (`roleID` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`roleID`)
    REFERENCES `CSTAlumniBoard`.`ROLE` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`FORUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`FORUM` (
  `forumID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `timeCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `userID` INT(11) NOT NULL,
  PRIMARY KEY (`forumID`),
  INDEX `fk_FORUM_USER1_idx` (`userID` ASC),
  CONSTRAINT `fk_FORUM_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`THREAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`THREAD` (
  `threadID` INT(11) NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(100) NULL DEFAULT NULL,
  `timeCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isPinned` TINYINT(1) NULL DEFAULT NULL,
  `userID` INT(11) NOT NULL,
  `forumID` INT(11) NOT NULL,
  PRIMARY KEY (`threadID`),
  INDEX `fk_THREAD_USER1_idx` (`userID` ASC),
  INDEX `fk_THREAD_FORUM1_idx` (`forumID` ASC),
  CONSTRAINT `fk_THREAD_FORUM1`
    FOREIGN KEY (`forumID`)
    REFERENCES `CSTAlumniBoard`.`FORUM` (`forumID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_THREAD_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`POST` (
  `postID` INT(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `timePosted` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isPinned` TINYINT(1) NULL DEFAULT NULL,
  `isQuestion` TINYINT(1) NULL DEFAULT NULL,
  `isReply` TINYINT(1) NULL DEFAULT NULL,
  `threadID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  `originalPostID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`postID`),
  INDEX `fk_POST_THREAD1_idx` (`threadID` ASC),
  INDEX `fk_POST_USER1_idx` (`userID` ASC),
  INDEX `fk_POST_POST1_idx` (`originalPostID` ASC),
  CONSTRAINT `fk_POST_POST1`
    FOREIGN KEY (`originalPostID`)
    REFERENCES `CSTAlumniBoard`.`POST` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POST_THREAD1`
    FOREIGN KEY (`threadID`)
    REFERENCES `CSTAlumniBoard`.`THREAD` (`threadID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POST_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`ATTACHMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`ATTACHMENT` (
  `attachmentID` INT(11) NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(45) NULL DEFAULT NULL,
  `fileType` VARCHAR(45) NULL DEFAULT NULL,
  `postID` INT(11) NOT NULL,
  PRIMARY KEY (`attachmentID`),
  INDEX `fk_ATTACHMENT_POST1_idx` (`postID` ASC),
  CONSTRAINT `fk_ATTACHMENT_POST1`
    FOREIGN KEY (`postID`)
    REFERENCES `CSTAlumniBoard`.`POST` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`FORUM_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`FORUM_SUBSCRIPTION` (
  `forumID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  UNIQUE INDEX `idx_forum_subscription_forumID_userID` (`forumID` ASC, `userID` ASC),
  INDEX `fk_forum_subscription_forum1_idx` (`forumID` ASC),
  INDEX `fk_forum_subscription_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_forum_subscription_forum1`
    FOREIGN KEY (`forumID`)
    REFERENCES `CSTAlumniBoard`.`FORUM` (`forumID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_subscription_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`NOTIFICATION` (
  `notificationID` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `threadID` INT(11) NULL DEFAULT NULL,
  `timeNotified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`notificationID`),
  INDEX `fk_Notification_user1_idx` (`userID` ASC),
  INDEX `fk_NOTIFICATION_thread1_idx` (`threadID` ASC),
  CONSTRAINT `fk_NOTIFICATION_thread1`
    FOREIGN KEY (`threadID`)
    REFERENCES `CSTAlumniBoard`.`THREAD` (`threadID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTIFICATION_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `CSTAlumniBoard`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CSTAlumniBoard`.`PRIVILEGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSTAlumniBoard`.`PRIVILEGE` (
  `privilegeID` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `roleID` INT(11) NOT NULL,
  PRIMARY KEY (`privilegeID`),
  INDEX `fk_PRIVILEGE_ROLE_idx` (`roleID` ASC),
  CONSTRAINT `fk_PRIVILEGE_ROLE`
    FOREIGN KEY (`roleID`)
    REFERENCES `CSTAlumniBoard`.`ROLE` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
